version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_DB=${DB_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  data_scraper:
    build:
      context: ./data_scraper
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_DB=${DB_DB}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

volumes:
  postgres_data: