services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  data_scraper:
    build:
      context: ./data_scraper
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_DB=${DB_DB}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db

volumes:
  postgres_data: